### PR TITLE
Ongoing AYP transform work

### PR DESCRIPTION
**Pull request by briesenberg07**
Closing this for now--previously-merged commits are showing up--I think I need to merge again before I create a new pull request?

### CODE REVIEW

**Comment by briesenberg07** [comment]
Still not sure why previously-merged pull requests are showing up. 
### Commit 3162847:
- Added triple to express rdf:type = dpla:SourceResource to sourceResource sub-template
- "Cleaned up" the transform, specifically
  - sub-templates for sourceResource and webResource:
    - Moving all rdf:Description elements down to CONTENTdm element templates
  - Agent, Aggregation, etc. classes appear in alphabetical order in transform to match the order in which output files are saved to disk after transform

**Comment by briesenberg07** [comment]
### Commit 720031c:
Created blank nodes for the output from the following Cdm elements:
- OrderNumber
- PhotographersReferenceNumber
- NegativeNumber
NOTE: We had talked about continuing to use dct:identifier > bnode for these elements. However, as dct:identifier has a range of Literal I thought it best to use the bf:identifiedBy property. Let's discuss.

**Comment by briesenberg07** [comment]
### Commit 2fa06c1:
- Added edm:isShownAt for the AYP digital collection using a variable at the top of the stylesheet

**Comment by briesenberg07** [comment]
### Commit fe66929:
Improved tokenizing for **SubjectsLctgm** and **SubjectsLcsh** values
Now tokenizes on a semicolon plus one or more whitespace characters

**Comment by briesenberg07** [comment]
### Commit 4390fb4:
- Added language tags for most elements mentioned in AYP questions document.
  - Some questions still remain--for example, are names/proper nouns and measurements in inches considered to be in a particular language?

**Comment by briesenberg07** [comment]
### Commit 654f89a:
- Added IRIs for UW Classes OrderNumber, NegativeNumber, PhotographersReferenceNumber to XSL

**Comment by briesenberg07** [comment]
### Commit 2e23f5d:
- Added language tags for output to dpla:providedLabel from the following Cdm elements:
  - Photographer
  - Repository
  - StudioName

**Comment by briesenberg07** [comment]
### Note:
Comments detailing commits seem superfluous as commit details can be displayed from this page easily. I'm going to stop posting comments reproducing information already included in the commits themselves.

**Comment by briesenberg07** [comment]
Hello @gerontakos 
Still not the final commit for the AYP transform--sorry if this is confusing. Will send notice when everything we've discussed has been done in the transform.

**Comment by briesenberg07** [comment]
@gerontakos 
### That's everything on the list!
I believe we are ready to merge and move on.
Output from the newest transform is in the [workingDraftRdfXml](https://drive.google.com/drive/folders/1TeAZxCwjwCPzFX7kxrjVwQ6loQ2cpW37?usp=sharing) folder. Once you've taken a look--assuming you don't find any issues--those files can be used by Crystal for SPARQL cleanup.

**Comment by gerontakos** [comment]
Great, thank you!

---------------------------------------------------------
nameOfSender=Theodore_Gerontakos
jobTitle=Metadata&#47;Cataloging_Librarian
cellPhone=206-276-6209
officePhone=206-543-8407
---------------------------------------------------------

**Comment by gerontakos** [comment]
squash and merge BR commits, establishing v.1 of cdm-2-rdf.xsl

**Pull request merged**
